# matrix operations
import numpy as np
x= np.array([[12,3,21],[2,43,5],[5,32,53]])
y= np.array([[11,4,6],[23,7,9],[4,8,43]])
a=np.multiply(x,y)
b=np.add(x,y)
c=np.transpose(x)
d=np.transpose(y)
print("multiplication of two matrices ")
print(a)
print("addition of matrices")
print(b)
print("transpose of matrices")
print(c)
print(d)
